/**
 * Alpaca Broker API
 * Open brokerage accounts, enable commission-free trading, and manage the ongoing user experience with Alpaca Broker API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models'

export class JournalData {
  'entry_type': JournalData.EntryTypeEnum
  'from_account': string
  'to_account': string
  'description'?: string | 'rejected' | 'pending'
  'transmitter_name'?: string
  'transmitter_account_number'?: string
  'transmitter_address'?: string
  'transmitter_financial_institution'?: string
  'transmitter_timestamp'?: string

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: 'entry_type',
      baseName: 'entry_type',
      type: 'JournalData.EntryTypeEnum'
    },
    {
      name: 'from_account',
      baseName: 'from_account',
      type: 'string'
    },
    {
      name: 'to_account',
      baseName: 'to_account',
      type: 'string'
    },
    {
      name: 'amount',
      baseName: 'amount',
      type: 'string'
    },
    {
      name: 'symbol',
      baseName: 'symbol',
      type: 'string'
    },
    {
      name: 'qty',
      baseName: 'qty',
      type: 'string'
    }
  ]

  static getAttributeTypeMap() {
    return JournalData.attributeTypeMap
  }
}

export namespace JournalData {
  export enum EntryTypeEnum {
    Jnlc = <any>'JNLC',
    Jnls = <any>'JNLS'
  }
}
